#https://source.developers.google.com/p/alert-flames-286515/r/github_rjones18_gcp-kubernetes-python-app

steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://source.developers.google.com/p/alert-flames-286515/r/github_rjones18_gcp-kubernetes-python-app']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t',  'gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}']

# kubectl set image deployment/cicd-app-1 nginx-1=gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}
- name: 'gcr.io/cloud-builders/kubectl'
  args :
  - 'set'
  - 'image'
  - 'deployment/cicd-app-1'
  - 'nginx-1=gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}'
  env : 
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cicd-cluster'

substitutions:
  _PROJECT_ID : alert-flames-286515
  _CINAME : gke-image
  _VERSION : v2.0

options:
  logging : CLOUD_LOGGING_ONLY
timeout: 1600s
